require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Creates a cat"
task :create do
  puts "Meow! I'm new!"
end
